version: "3.0"
services:

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    networks:
      - es-net
    ports:
      - 9200:9200
      
  kibana:
    image: kibana:7.10.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

networks:
  es-net:
    driver: bridge