version: '3.8'
volumes:
  mongo_data:
services:
  
  mongowebapi:
    image: mongowebapi
    build: 
      context: ./SimpleWebAPIProjectThamplate
      dockerfile: Dockerfile
  #  depends_on:
  #    - mongo_db

  #mongo_db:
  #  image: mongo
  #  restart: always
  #  environment:
  #    MONGO_INITDB_ROOT_USERNAME: root
  #    MONGO_INITDB_ROOT_PASSWORD: example
  #  ports:
  #    - 27017:27017
  #
  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  volumes:
  #    - mongo_data
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #    ME_CONFIG_MONGODB_URL: mongo_db://root:example@mongo_db:27017/
  #